class ScheduleSerializer < ActiveModel::Serializer
  attributes :id,
    :store_id,
    :store_name,
    :course_id,
    :course_type_name,
    :course_name,
    :course_description,
    :start_time,
    :end_time,
    :capacity,
    :is_published,
    :time_stage,
    :booked_number,
    :waiting_number,
    :complete_number ,
    :bookable,
    :waitable,
    :updated_at
end
