default: &default
  adapter: postgresql #mysql2
  encoding: utf8
  username: chenxi
  password:
  pool: 5
  host: localhost

development:
  <<: *default
  database: commonstrength_dev

test:
  <<: *default
  database: commonstrength_test

production:
  <<: *default
  database: commonstrength
